### ISSUE TITLE
Restart this crappy router every night

### ISSUE THREAD

**Issue by JosXa** [home-assistant-ecosystem/python-connect-box#18]
So I thought for sure someone has written a library to interact with the web interface of my ~shitty~ lackluster Unitymedia router, and voila, stumbled over this gem. Nice job on the type hints and use of attribs, very well written from my first impression flying over the code.

So the idea I had was to remotely control the web interface to restart the router on demand when it's been filling up its connections again and won't accept new requests, or just do the same every night on a schedule. I was wondering if anyone has done this before or got any tips on how to implement it before I get started hacking? :)

If I manage to do it, you'll probably see a PR coming in.

**Comment by artudi54** [comment]
I have just made such script today. Basicaly fun=8 means reset. You can check this out here.
[connectbox](https://github.com/artudi54/connectbox)

**Comment by JosXa** [comment]
Solved using the alternative library from #12 where it is a one-liner :)
