### ISSUE TITLE
self._session: aiohttp.ClientSession = session: SyntaxError

### ISSUE THREAD

**Issue by av01d** [home-assistant-ecosystem/python-connect-box#22]
Fresh install, trying to run example.py:
```
[pi@pi:~scripts]% python3 example.py 
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from connect_box import ConnectBox
  File "/home/pi/.local/lib/python3.5/site-packages/connect_box/__init__.py", line 52
    self._session: aiohttp.ClientSession = session
                 ^
SyntaxError: invalid syntax
```
This is using python version 3.5.3.
Is this a bug, or do I do something wrong (I admittedly don't know much about Python).

**Comment by av01d** [comment]
I presume that I need to upgrade Python to version 3.6 or newer? 
Too bad Raspbian comes with 3.5.3. Upgrading is messy and takes forever.

**Comment by av01d** [comment]
Anyone looking for a simple script to just retrieve the connected clients on the Compal box:
https://gist.github.com/av01d/940a498063427975616d22dc91401cda

**Comment by fabaff** [comment]
In the beginning there was support for 3.4. Nowadays, later Python releases are needed.

Sorry for the inconvenience.
